// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqKbhq0pWsnI10mjP5q6_aBflwObZHzk',
    appId: '1:640166225886:web:ee158a4919461978731f4f',
    messagingSenderId: '640166225886',
    projectId: 'notely-9a3f5',
    authDomain: 'notely-9a3f5.firebaseapp.com',
    storageBucket: 'notely-9a3f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAjgMgiz-98UVkCbGlblbY9ykQN8slio',
    appId: '1:640166225886:android:b32252ca11ba88d8731f4f',
    messagingSenderId: '640166225886',
    projectId: 'notely-9a3f5',
    storageBucket: 'notely-9a3f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76OUYYoWH2Pq8l8vcEoVauHW5PhWdpqs',
    appId: '1:640166225886:ios:1eb69f8ad48e365c731f4f',
    messagingSenderId: '640166225886',
    projectId: 'notely-9a3f5',
    storageBucket: 'notely-9a3f5.appspot.com',
    iosClientId: '640166225886-apln4r8bdmau8hr75vakl2kuc4t6l855.apps.googleusercontent.com',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB76OUYYoWH2Pq8l8vcEoVauHW5PhWdpqs',
    appId: '1:640166225886:ios:1eb69f8ad48e365c731f4f',
    messagingSenderId: '640166225886',
    projectId: 'notely-9a3f5',
    storageBucket: 'notely-9a3f5.appspot.com',
    iosClientId: '640166225886-apln4r8bdmau8hr75vakl2kuc4t6l855.apps.googleusercontent.com',
    iosBundleId: 'com.example.notely',
  );
}
